name: Run Watchdog

on:
  schedule:
    # 8:00 PM PKT = 3:00 PM UTC
    - cron: '0 15 * * *'

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  run-watchdog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x watchdog.sh

      - name: Run Watchdog
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: ./watchdog.sh
